spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_db_tests?useTimezone=true&serverTimezone=UTC
    username: springBootTests
    password: '@Spring123'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    baselineOnMigrate: true

spring-doc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true